export default {
  'START_SERVER': 'START_SERVER',
  'CREATE_SERVER': 'CREATE_SERVER',
  'ERROR_SERVER': 'ERROR_SERVER',
  'UPDATE_CONTEXT': 'UPDATE_CONTEXT',
  'REMOVE_CONTEXT': 'REMOVE_CONTEXT',
  'STOP_SERVER': 'STOP_SERVER'
}